Another update to try and catch more instances where pkgs aren't being fetched / downloaded properly before we start an update.

diff --git a/pc-updatemanager b/pc-updatemanager
--- a/pc-updatemanager
+++ b/pc-updatemanager
@@ -1434,7 +1434,9 @@ dl_pkgs()
   echo "Verifying / fetching packages for ports-mgmt/pkg - $PKGFILENAME" >> ${PKGUPGRADELOG}
   ${PKG_CMD} ${PKG_CFLAG} ${PKG_FLAG} update | tee -a ${PKGUPGRADELOG}
   ${PKG_CMD} ${PKG_CFLAG} ${PKG_FLAG} fetch -U -d -y ports-mgmt/pkg 2>&1 | tee -a ${PKGUPGRADELOG}
-  if [ $? -ne 0 ] ; then
+  _err=$?
+  tail -n 1 ${PKGUPGRADELOG} | grep -q "failed checksum"
+  if [ $_err -ne 0 -o $? -eq 0 ]; then
      if [ -e "/usr/local/bin/pc-systemflag" ] ; then
        pc-systemflag PKGUPDATE ERROR
      fi
@@ -1464,8 +1466,10 @@ dl_pkgs()
   SYSBASEFILENAME="`${PKG_CMD} ${PKG_FLAG} rquery -U '%n-%v' $SYSBASE 2>/dev/null | head -n 1`.txz"
   echo_log "Verifying / fetching packages for ${SYSBASE} - $SYSBASEFILENAME"
   echo "Verifying / fetching packages for ${SYSBASE} - $SYSBASEFILENAME" >> ${PKGUPGRADELOG}
-  ${PKG_CMD} ${PKG_CFLAG} ${PKG_FLAG} fetch -U -d -y ${SYSBASE} 2>&1 | tee  -a ${PKGUPGRADELOG}
-  if [ $? -ne 0 ] ; then
+  ${PKG_CMD} ${PKG_CFLAG} ${PKG_FLAG} fetch -U -d -y ${SYSBASE} 2>&1 >${PKGUPGRADELOG}
+  _err=$?
+  tail -n 1 ${PKGUPGRADELOG} | grep -q "failed checksum"
+  if [ $_err -ne 0 -o $? -eq 0 ]; then
      if [ -e "/usr/local/bin/pc-systemflag" ] ; then
        pc-systemflag PKGUPDATE ERROR
      fi
@@ -1514,37 +1518,43 @@ dl_pkgs()
     # Fetch the pkg now
     echo_log "Verifying / fetching packages for ${pkgOrigin} - $FETCHFILENAME"
     echo "Verifying / fetching packages for ${pkgOrigin} - $FETCHFILENAME" >> ${PKGUPGRADELOG}
-    ${PKG_CMD} ${PKG_CFLAG} ${PKG_FLAG} fetch -U -d -y $pkgOrigin 2>&1 | tee -a ${PKGUPGRADELOG}
+    ${PKG_CMD} ${PKG_CFLAG} ${PKG_FLAG} fetch -U -d -y $pkgOrigin 2>&1 >${PKGUPGRADELOG}
     # PKGNG lies, we need to verify if the package was really downloaded as well
-    if [ $? -ne 0 ] || [ ! -e "${REALPKGDLCACHE}/${FETCHFILENAME}" ] ; then
+    _err=$?
+    tail -n 1 ${PKGUPGRADELOG} | grep -q "failed checksum"
+    if [ $_err -ne 0 -o $? -eq 0 -o ! -e "${REALPKGDLCACHE}/${FETCHFILENAME}" ]; then
       #Try one more time
       sleep 2
       echo_log " - Failure: Trying again"
       echo " - Failure: Trying again" >> ${PKGUPGRADELOG}
-      ${PKG_CMD} ${PKG_CFLAG} ${PKG_FLAG} fetch -U -d -y $pkgOrigin 2>&1 | tee -a ${PKGUPGRADELOG}
+      ${PKG_CMD} ${PKG_CFLAG} ${PKG_FLAG} fetch -U -d -y $pkgOrigin 2>&1 >${PKGUPGRADELOG}
+      _err=$?
+      tail -n 1 ${PKGUPGRADELOG} | grep -q "failed checksum"
+      if [ $_err -ne 0 -o $? -eq 0 -o ! -e "${REALPKGDLCACHE}/${FETCHFILENAME}" ]; then
        #Check again for success
-       if [ $? -ne 0 ] || [ ! -e "${REALPKGDLCACHE}/${FETCHFILENAME}" ] ; then
-         echo_log " - Failed again: Try again later"
-	 echo " - Failed again: Try again later" >> ${PKGUPGRADELOG}
-         echo_log "*****" ${PKGUPGRADELOG}
-         echo_log "Failed fetching: $pkgOrigin" >> ${PKGUPGRADELOG}
-         exit_err "Failed fetching: $pkgOrigin"
-       fi
+        echo_log " - Failed again: Try again later"
+        echo " - Failed again: Try again later" >> ${PKGUPGRADELOG}
+        echo_log "*****" ${PKGUPGRADELOG}
+        echo_log "Failed fetching: $pkgOrigin" >> ${PKGUPGRADELOG}
+        exit_err "Failed fetching: $pkgOrigin"
+      fi
     fi
 
     echo "$pkgOrigin $FETCHFILENAME" >> $NEWPKGLIST
   done < $OLDPKGLIST
 
   if [ "$1" = "pkg" ] ; then
-    ${PKG_CMD} ${PKG_CFLAG} ${PKG_FLAG} upgrade -U -F -y 2>&1 | tee -a ${PKGUPGRADELOG}
+    ${PKG_CMD} ${PKG_CFLAG} ${PKG_FLAG} upgrade -U -F -y 2>&1 >${PKGUPGRADELOG}
   fi
 
   # Doing a world upgrade, lets fetch FreeBSD packages
   if [ "$1" = "world" ] ; then
     echo_log "Verifying / fetching packages for FreeBSD Base"
     echo "Verifying / fetching packages for FreeBSD Base" >> ${PKGUPGRADELOG}
-    ${PKG_CMD} ${PKG_CFLAG} ${PKG_FLAG} fetch -U -d -y -g 'FreeBSD-*' 2>&1 | tee -a ${PKGUPGRADELOG}
-    if [ $? -ne 0 ]; then
+    ${PKG_CMD} ${PKG_CFLAG} ${PKG_FLAG} fetch -U -d -y -g 'FreeBSD-*' 2>&1 >${PKGUPGRADELOG}
+    _err=$?
+    tail -n 1 ${PKGUPGRADELOG} | grep -q "failed checksum"
+    if [ $_err -ne 0 -o $? -eq 0 ]; then
       echo_log "*****" ${PKGUPGRADELOG}
       echo_log "Failed fetching: FreeBSD Base" >> ${PKGUPGRADELOG}
       exit_err "Failed fetching: FreeBSD Base"
